# Generated by Django 3.1.2 on 2020-10-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminupload', models.FileField(upload_to='media')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
