# Generated by Django 3.1.2 on 2020-10-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_auto_20201012_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='image_url',
            field=models.CharField(default='https://www.google.com/search?q=pdf+image&sxsrf=ALeKk00TsM1YLise0DmIrfwlPtxYQKzKxw:1602515629906&tbm=isch&source=iu&ictx=1&fir=n9C4o-1uSvCB7M%252CKWiraILIbCtt4M%252C_&vet=1&usg=AI4_-kTUqCU6dGWC5W4O_7KJUet4eeKZzg&sa=X&ved=2ahUKEwio9ff2q6_sAhXK6OAKHXlZDEIQ9QF6BAgPEF8#imgrc=n9C4o-1uSvCB7M', max_length=2083),
            preserve_default=False,
        ),
    ]
