# Generated by Django 3.1.2 on 2020-10-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_recipes_recipe_of_the_week'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
